---
title: "Contrôle de source avec git"
author:
  - name: Eric Marcon
abstract: >
  L'objectif du cours est d'utiliser simplement et efficacement git pour le suivi de version et le travail collaboratif avec RStudio.
date: "`r format(Sys.time(), '%d %B %Y')`"
pdftoc: yes
preamble: >
  \usepackage{textcomp}
  \DeclareUnicodeCharacter{B0}{\textdegree}
  \hyphenation{bio-di-ver-si-ty sap-lings}
lang: french # english
bibliography: references.bib
output:
  bookdown::gitbook: 
    config:
      download: 
        - ["Cours-git.pdf", "PDF"]
  bookdown::word_document2: default
  bookdown::pdf_book:
    base_format: EcoFoG::memo
    keep_tex: TRUE
---

<!-- Options de knitr et de R (librairies, ...) --> 

```{r Options, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy=TRUE, tidy.opts=list(blank=FALSE, width.cutoff=50), out.width='.8\\maxwidth')
options(width=50)
# Installation des packages si nécessaire et chargement
Library <- function(Packages) {
  InstallAndLoad <- function(Package) {
    if (!Package %in% installed.packages()[, 1]) {install.packages(Package, repos="https://cran.rstudio.com/")}
    require(Package, character.only = TRUE)
  }
  invisible(sapply(Packages, InstallAndLoad))
}
# Ajouter les packages nécessaires ici
Library(c("kableExtra", "tidyverse"))
```

<!-- Début du document ci-dessous --> 


# Introduction

_git_ est devenu l'outil standard de contrôle de source.
Il est complètement intégré à RStudio, ce qui le rend simple à utiliser au-delà de son audience historique de développeurs.
Enfin, _GitHub_ est devenue la plateforme de partage de code dominante, avec des services haut de gamme et gratuits comme la fourniture d'un site web de présentation pour chaque projet, l'accès à des outils d'intégration continue comme _TravisCI_ et _CodeCov_.


# Données confidentielles dans un dépôt public

Le partage sur _GitHub_ dans un dépôt public pose problème quand des données utilisées dans le projet ne sont pas publiques.

Une solution peu satisfaisante consiste à ne pas inclure les données au projet, ce qui le rend non reproductible.
Une meilleure solution est de les crypter, en permettant à certains utilisateurs de les décrypter.
C'est l'objet du package _secret_.


